### ISSUE TITLE
Insertion order of keys

### ISSUE THREAD

**Issue by ziggi** [BridgeAR/safe-stable-stringify#17]
Is it possible to make this lib to return insertion order of keys? In some cases it's important.

**Comment by ziggi** [comment]
So, I just do this: https://github.com/BridgeAR/safe-stable-stringify/commit/0eff168dd767fadbb031f4bd629b8f6d168cd7a9, it's fine?

**Comment by WangHansen** [comment]
Agreed, @ziggi maybe a PR?

**Comment by BridgeAR** [comment]
I added a option to deactivate the deterministic behavior and it's going to be released in v2.0.0.

**Comment by BridgeAR** [comment]
I just released the new version.
