### ISSUE TITLE
Not compatible with ES5

### ISSUE THREAD

**Issue by c4ndybar** [BridgeAR/safe-stable-stringify#2]
Could we transpile this down to es5 so it is compatible with older browsers?  The code appears to be ES6/7 compliant currently.

**Comment by BridgeAR** [comment]
The features used in this module should be supported by pretty much all browsers with a usage > 0.5%. Are you really facing difficulties with users that use very outdated browsers?

**Comment by c4ndybar** [comment]
Unfortunately, I have to target IE11 (which according to [this site](http://gs.statcounter.com/browser-market-share) still has ~3% market share).  You can see [here](http://kangax.github.io/compat-table/es6/) that IE11 has almost no support for es6+ features.

I'm using a manually transpiled version right now, but that's obviously not ideal.  I'd appreciate if you could transpile the library if it's not too much trouble.

**Comment by BridgeAR** [comment]
@c4ndybar I added support for IE11 by removing the arrow function and `let`. This should be enough to target IE11. Please let me know if you run into any issues. Thanks.
