### ISSUE TITLE
Ability to remove Circular references

### ISSUE THREAD

**Issue by thetutlage** [BridgeAR/safe-stable-stringify#23]
I looked at the existing issues and the README. Both doesn't mention any specific reason for not removing Circular reference (optionally). 

So lemme start by asking, if it is possible to optionally allow removing Circular references all together from the output, or is this something a design choice that impacts the goals (usually performance) of this package?

**Comment by thetutlage** [comment]
Yup, that looks good. Thanks :)

**Comment by BridgeAR** [comment]
Fixed by #24 and published as v2.2.0.
