### ISSUE TITLE
The function stringifies only one level

### ISSUE THREAD

**Issue by quaos** [BridgeAR/safe-stable-stringify#30]
Sample code:

```ts
import safeStringify from 'safe-stable-stringify';

const stringifier = safeStringify.configure({
  deterministic: true,
  circularValue: undefined,
  maximumDepth: 99,
});

const result = stringifier(
  {
    result: {
      a: true,
      b: '2',
      c: { cc: 33 },
    },
    lastError: new Error('test serializing errors'),
    success: true,
  },
  ['success', 'result', 'lastError', 'lastError.message']
);

console.log(result);
```

The output is:
```
{"success":true,"result":{},"lastError":{}}
```

Using without `configure` still outputs the same.

Package version: 2.3.1
TypeScript version: 4.7.4
Node version: v17.4.0

**Comment by BridgeAR** [comment]
The output seems correct to me? JSON.stringify also behaves exactly the same.

The second argument is an array of strings naming keys of the input argument that should be stringified. All other properties are ignored. `'lastError.message'` will only match the exact key name as complete string. You likely want to use `'message'` instead.
