### ISSUE TITLE
Type Definition Not Accurate

### ISSUE THREAD

**Issue by alexlafroscia** [BridgeAR/safe-stable-stringify#35]
I ran into an issue today due to a discrepancy between the type definitions and the actual behavior of the library that I thought might be useful to make an issue about.

The type definitions claim that the `stringify` function _always_ returns a string...

https://github.com/BridgeAR/safe-stable-stringify/blob/73a49c28d60663b3e4be6a6bd0eb95e83d173369/index.d.ts#L1-L2

...but that's not actually true! Much like `JSON.stringify`, `safe-stable-stringify` returns `undefined` when passed `undefined`

```js
const stringify = require('safe-stable-stringify');

stringify(undefined); // undefined
```

This is fine behavior, as far as I'm concerned, especially since `JSON.stringify` does the same thing. However, I think it would be useful for the type definition to reflect this, since it's easy to assume that the function always returns a `string` with the type definition written the way that it is!

**Comment by BridgeAR** [comment]
Thanks a lot for bringing this up. You are absolutely right!

I just had a look at it and I will update the definition in a way that most values are detected as either `string` or `undefined` and few cases report as `string | undefined`. The latter should only apply to bigint values and where users use a replacer function with values that could end up as undefined value.
