### ISSUE TITLE
latest version of index.js has syntax error that causes issue for winston@3.8.2

### ISSUE THREAD

**Issue by bluesweater** [BridgeAR/safe-stable-stringify#38]
Hi there,

I am using **gulp-svg-sprite@1.5.0** which uses **svg-sprites@1.5.4** which uses **winston@3.8.2** which uses **safe-stable-stringify@2.4.1**

It threw an error "SyntaxError : Unexpected token ..." at index.js:214 - it didn't like the `...` from  `...options` which is from the commit https://github.com/BridgeAR/safe-stable-stringify/commit/f001e74a77e64a486b540a6628e39fc21918eb14

I googled and this other person also had this issue -> https://github.com/winstonjs/winston/issues/2201#issuecomment-1251596182 ; that person suggested that v2.3.1 is stable for them (as seen higher up in that ticket).

Pls look into this if you have time to do so. Thank you for your time and effort regardless.

**Comment by amirhosseinkabiri** [comment]
I had the same error and it was just because of node.js version. installing node.js using yum is wrong! cause it installs the 6.x version. I followed the second method of [this link](https://linuxgenie.net/how-to-install-node-js-on-centos-8/) and everything works.
