### ISSUE TITLE
undefined type makes it hard to use the library

### ISSUE THREAD

**Issue by gajus** [BridgeAR/safe-stable-stringify#40]
```
stringify({
  date: 1_657_114_107,
  ip: '82.4.109.159',
  user_agent:
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
})
```

This produces `string | undefined`.

I would really like a version of this package that never produces `undefined`, i.e. throws an error if the result is undefined.

The way we workaround this locally is by wrapping the `stringify` method in `safeStringify`:

```ts
import stringify from 'safe-stable-stringify';

export const safeStringify = (subject: unknown): string => {
  const result = stringify(subject);

  if (result === undefined) {
    throw new Error('Expected result to be string');
  }

  return result;
};
```

**Comment by BridgeAR** [comment]
This sounds like you are looking for the `strict` option? It is going to throw an error in case anything is passed through that can not be represented as JSON besides `undefined` itself. That would still result in `undefined`.

TypeScript should handle the above input as `string` in case the wrapper would not be used (it declares the subject as `unknown`). It detects that it's an object and that can only return a string.

**Comment by BridgeAR** [comment]
Ping @gajus

**Comment by gajus** [comment]
Indeed. Strict option is what I was after. Thank you
