### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RamiAPFM** [BridgeAR/safe-stable-stringify#41]
```node_modules/safe-stable-stringify/index.js:287:23```

```for (let i = 0; i < maximumPropertiesToStringify; i++) {
          const key = keys[i]
          const tmp = stringifyFnReplacer(key, value, stack, replacer, spacer, indentation)
          if (tmp !== undefined) {
            res += `${separator}"${strEscape(key)}":${whitespace}${tmp}`
            separator = join
          }
        }
```
        
 It appears I am experiencing a memory leak when attempting to log circular JSON.

Any advice on how to tackle this?

Dependencies:

```"devDependencies": {
    "@types/newrelic": "^9.4.0",
    "@typescript-eslint/eslint-plugin": "^5.42.0",
    "@typescript-eslint/parser": "^5.42.0",
    "eslint": "^8.27.0",
    "eslint-plugin-import": "^2.26.0",
    "prettier": "^2.7.1",
    "prettier-plugin-organize-imports": "^3.1.1",
    "standard-version": "^9.5.0",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^4.8.4"
  },
  "dependencies": {
    "@types/compression": "^1.7.2",
    "@types/config": "^3.3.0",
    "@types/connect-slashes": "0.0.33",
    "@types/connect-timeout": "0.0.36",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.14",
    "@types/response-time": "^2.3.5",
    "body-parser": "1.20.1",
    "compression": "1.7.4",
    "config": "3.3.8",
    "connect-slashes": "1.4.0",
    "connect-timeout": "1.9.0",
    "cookie-parser": "1.4.6",
    "dotenv": "16.0.3",
    "express": "4.18.2",
    "https": "^1.0.0",
    "newrelic": "^9.7.1",
    "response-time": "2.3.2",
    "winston": "^3.8.2",
    "winston-transport-sentry-node": "^2.6.0"
  },```

**Comment by BridgeAR** [comment]
Do you have the code that caused the issue? The code does detect circular structures.

**Comment by RamiAPFM** [comment]
```":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_des^Cestroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":{"_destroyed":false,"_idleNext":"[Circular]","_idlePrev":"[Circular]","_idleStart":76374,"_idleTimeout":40000,"_repeat":null},"_idleStart":76374,"_idleTimeout":40000,"_repeat":null},"_idleStart":76374,"_idleTimeout":40000,"_repeat":null},"_idleStart":76374,"_idleTimeout":40000,"_repeat":null},"_idleStart":76374,"_idleTimeout":40000,"_repeat":null},"_idleStart":76363,"_idleTimeout":40000,"_repeat":null},"_idleStart":76363,"_idleTimeout":40000,"_repeat":null},"_idleStart":76363,"_idleTimeout":40000,"_repeat":null},"_idleStart":763```

**Comment by BridgeAR** [comment]
This looks like a linked list and the maximum call stack size is not related to a circular structure in this case. The algorithm uses a recursion and this adds up while trying to create the JSON representation of this deep linked list. You can use the `maximumDepth` option to limit the inspection to a specific depth. Logging a linked list is a bit tricky though and I wonder if that is really what you want to do.

Rewriting the algorithm to a non recursive one would also resolve the issue but that is likely a bit slower and a bit more complicated to implement. I would rather not do that at the moment.

I am going to lose this as there's nothing else that I can do at the moment. Maybe still let me know if using the `maximumDepth` option helps you? :-)

**Comment by RamiAPFM** [comment]
pino.js uses a different library and the performance is significantly more performant and this issue doesn't exist there.
