### ISSUE TITLE
array in benchmark seems incorrect

### ISSUE THREAD

**Issue by gmaclennan** [BridgeAR/safe-stable-stringify#45]
The [array used in the benchmark](https://github.com/BridgeAR/safe-stable-stringify/blob/main/benchmark.js#L8) is an array of length `2`, with the first entry as `{ length: 10 }` and the second entry `(_, i) => i`. Is this intended? It seems like what you would want for the benchmark is `Array(10).fill(null).map((_, i) => i)`.

**Comment by BridgeAR** [comment]
Good catch! It should be `Array.from()`.

**Comment by BridgeAR** [comment]
Fixed by 46f24495221803b7a945883cb8fb262b14f1ea52
