### ISSUE TITLE
safe-stable-stringfy giving slower results testing with console.time

### ISSUE THREAD

**Issue by arataqueh** [BridgeAR/safe-stable-stringify#47]
Hello,

I have noticed that when simply testing performance with console.time console.timeEnd, I see that safe-stable-stringify in most cases give a slower results with large object sizes. With a data worth 643 kB these are the results I get between these libs:

attempt 1
fast-safe-stringify: 5.02ms
safe-stable-stringify: 20.471ms
safe-json-stringify: 8.814ms

attempt 2
fast-safe-stringify: 5.797ms
safe-stable-stringify: 14.718ms
safe-json-stringify: 5.857ms

attempt 3
fast-safe-stringify: 5.602ms
safe-stable-stringify: 10.114ms
safe-json-stringify: 8.649ms

attempt 4
fast-safe-stringify: 4.631ms
safe-stable-stringify: 7.409ms
safe-json-stringify: 4.345ms

attempt 5
fast-safe-stringify: 4.643ms
safe-stable-stringify: 8.538ms
safe-json-stringify: 6.457ms

I am basically just removing circularValue in configure function and converting back to object format. This activity is happening to all libs above:

const stringify = configure({
  circularValue: undefined,
});

export const scrubCircularRefs = (obj) => {
  const stringifiedEntry = stringify(obj);
  return JSON.parse(stringifiedEntry);
};

Let me know if I missed any other thing in configure settings to make it more performant.

**Comment by BridgeAR** [comment]
Can you please share the object that you tested this with, what V8 version / Node.js version, what OS you ran this upon and the CPU used?

**Comment by BridgeAR** [comment]
I just had a look at it and the comparison is somewhat off. The mentioned libraries are not providing a deterministic output. This may be turned off here by defining `deterministic: false`. That should roughly bring the same speed to all of these. It overall depends on the concrete input which library will be fastest.
