### ISSUE TITLE
Feature Request: Allow customizing the sort order

### ISSUE THREAD

**Issue by flobernd** [BridgeAR/safe-stable-stringify#48]
Hi @BridgeAR,

we have a use-case that requires to emit JSON objects with a specific deterministic key order. All keys should be ordered alphabetically, except for a single key which should always be emitted first. This specific key is used as a discriminator for polymorphic objects and the deserialization framework requires this key to be always the first one in the object.

The possibility to pass a "comparator" lambda function for the key names, similar to `sort()` would be great. As a bonus, it would be nice to have access to the source object from inside the lambda function (e.g. to have different discriminator names based on the type of the object).

**Comment by BridgeAR** [comment]
It would be possible to overload the `determinstic` option to accept a lambda function as comparator. That would not slow down the overall code (note: [typed] arrays are not passed to such comparator).

A comparator should ideally behave identical to the `Array#sort(comparator)`. Having access to the source object is therefore not ideal. It would have to pretty much receive a third argument. But imagine the native comparator would at some point receive a third argument that would behave differently. That would not be ideal. Is that definitely needed?

**Comment by flobernd** [comment]
@BridgeAR Thanks for the fast response. 

Allowing us to pass a `Array#sort(comparator)` compatible comparator to the `deterministic` function would help us a lot! Currently, the discriminator fields do all share the same name. 

We can always iterate over this at a later point again, if we ever encounter a more complex scenario that requires access to the source object (probably this will never happen anyways) 🙂

**Comment by BridgeAR** [comment]
Please feel free to open a PR that overloads the `deterministic` option.
